### PR TITLE
added pymug + icons(fb, twitter, linkedin)

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by cedpoilly** [comment]
@Abdur-rahmaanJ  Just needs some CSS:

image

**Comment by Abdur-rahmaanJ** [comment]
@cedpoilly because @MrSunshyne told me css later, like i also included link in the text but it's not displaying anything. I propose add css later.

**Comment by cedpoilly** [comment]
@MrSunshyne

**Comment by Abdur-rahmaanJ** [comment]
Just added some CSS nevertheless

**Comment by Abdur-rahmaanJ** [comment]
pymug_social_devcon

**Comment by MrSunshyne** [comment]
Merging. 
thanks for add the CSS also!

**Pull request merged**
