### PR TITLE
🍟Sponsor Section Optimisations

### PR DESCRIPTION
**Pull request by arwinneil**
Unintuitive `zoom` by design due to png sizes

### CODE REVIEW

**Comment by arwinneil** [comment]
Looks good @arwinneil

**Comment by arwinneil** [comment]
Thanks @arwinneil ! 👍

**Comment by MrSunshyne** [comment]
Uhhhh, wait, let me ask for some peer review. 

@MrSunshyne mind checking this?

**Comment by MrSunshyne** [comment]
thanks for tagging me @MrSunshyne, the PR looks ok !

**Comment by MrSunshyne** [comment]
image

**Pull request merged**
